services:
  # homepage:
  #   image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-homepage
  #   container_name: homepage-container
  #   ports:
  #     - 80:4321
  #   networks:
  #     - fitness-network

  webapi:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-webapi
    container_name: webapi-container
    ports:
      - 5000:8080
    networks:
      - fitness-network

  reactnative-web:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-phone-app-web
    container_name: reactnative-web-container
    ports:
      - 4000:8081
    networks:
      - fitness-network

networks:
  fitness-network:
    name: fitness-network
