services:
  phone-web:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest
    ports:
      - "4000:4000"
    container_name: phone-web-fitness-app-react-native
    networks:
      - fitness-app-network

  backend:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest
    ports:
      - "3000:3000"
    container_name: server-fitness-app-tsx
    networks:
      - fitness-app-network
    environment:
      - "DB_CONN_STRING=mongodb://database-fitness-app-mongodb:27017"

  database:
    image: mongodb/mongodb-community-server
    container_name: database-fitness-app-mongodb
    networks:
      - fitness-app-network

networks:
  fitness-app-network:
    driver: bridge
