services:
  phone-web:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest
    ports:
      - "4000:3000"
    container_name: phone-web
    networks:
      - fitness-app-network
    environment:
      EXPO_PUBLIC_IS_DEV: "no"

  backend:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest
    ports:
      - "3000:3000"
    container_name: backend
    networks:
      - fitness-app-network
    environment:
      FATSECRET_CONSUMER_KEY: ${FATSECRET_CONSUMER_KEY}
      FATSECRET_CONSUMER_SECRET: ${FATSECRET_CONSUMER_SECRET}
      IS_DEV: "no"
    depends_on:
      database:
        condition: service_started
        restart: true

  database:
    image: mongodb/mongodb-community-server
    container_name: database
    ports:
      - "27017:27017"
    networks:
      - fitness-app-network

networks:
  fitness-app-network:
    driver: bridge
