services:
  phone-web:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest
    ports:
      - "4000:3000"
    container_name: phone-web
    networks:
      - fitness-app-network
    environment:
      EXPO_PUBLIC_IS_DEV: "no"

  backend:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest
    ports:
      - "3000:3000"
    container_name: backend
    networks:
      - fitness-app-network
    environment:
      FATSECRET_CONSUMER_KEY: ${FATSECRET_CONSUMER_KEY}
      FATSECRET_CONSUMER_SECRET: ${FATSECRET_CONSUMER_SECRET}
      MONGO_DB_CONNECTION_STRING: ${MONGO_DB_CONNECTION_STRING}


networks:
  fitness-app-network:
    driver: bridge
