services:
  phone-web:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest
    restart: unless-stopped
    ports:
      - "4000:80"
    container_name: phone-web
    networks:
      - fitness-network
    depends_on:
      - backend

  backend:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    container_name: backend
    networks:
      - fitness-network
    environment:
      FATSECRET_CONSUMER_KEY: ${FATSECRET_CONSUMER_KEY}
      FATSECRET_CONSUMER_SECRET: ${FATSECRET_CONSUMER_SECRET}
      MONGO_DB_CONNECTION_STRING: ${MONGO_DB_CONNECTION_STRING}
    dns:
      - 8.8.8.8

networks:
  fitness-network:
    driver: bridge
