services:
  phone-web:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest
    ports:
      - "4000:3000"
    container_name: phone-web-fitness-app-react-native
    networks:
      - fitness-app-network

  backend:
    image: ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest
    ports:
      - "3000:3000"
    container_name: server-fitness-app-tsx
    networks:
      - fitness-app-network
    environment:
      FATSECRET_CONSUMER_KEY: ${FATSECRET_CONSUMER_KEY}
      FATSECRET_CONSUMER_SECRET: ${FATSECRET_CONSUMER_SECRET}

  database:
    image: mongodb/mongodb-community-server
    container_name: database-fitness-app-mongodb
    networks:
      - fitness-app-network

networks:
  fitness-app-network:
    driver: bridge
