name: Dockerize and Push

on: push

# on:
#   push:
#     branches: ["main"]

jobs:
  dockerize:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build images
      #   run: |
      #     cd code && \
      #     docker build -t ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest -f Dockerfile.server . && \
      #     docker build -t ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest -f Dockerfile.mobile .

      # - name: Push images
      #   run: |
      #     docker push ghcr.io/fitnessapp-clemens-and-yanni/fitness-server:latest && \
      #     docker push ghcr.io/fitnessapp-clemens-and-yanni/fitness-mobile:latest

      - name: Deploy remote using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: 64.227.116.189
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: whoami
