name: Push to Main GitHub Workflow Action

run-name: ${{ github.actor }} is pushing to main and "Push to Main GitHub Workflow Action" is running

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install dependencies
        run: pnpm install

      - name: Running tests
        run: pnpm build

      - name: Running tests
        run: pnpm test
